CUSTOM_FIXES = {
    "ai": "AI",
    "Ai": "AI",
    "AI": "AI",
    "plz": "please",
    "pls": "please",
    "world wal 2": "World War 2",
    "world war 2": "World War 2",
    "world war two": "World War 2",
    "world wal 1": "World War 1",
    "world war 1": "World War 1",
    "world war one": "World War 1",
    "hallo": "hello",
    "halo": "hello",
    "solv":"solve",
    "yo": "you",
    "abou": "about",
    "wal": "war",
    "whats": "what's",
    "wether": "weather",
    "problam": "problem",
    "shoul": "should",
    "slov": "solve",
    "cn": "can",
    "pls": "please",
    "recieve": "receive",
    "definately": "definitely",
    "teh": "the",
    "adress": "address",
    "occurence": "occurrence",
    "goverment": "government",
    "seperated": "separated",
    "enviroment": "environment",
    "langauge": "language",
    "inconvienent": "inconvenient",
    "acommodate": "accommodate",
    "tommorow": "tomorrow",
    "thier": "their",
    "wierd": "weird",
    "becuase": "because",
    "untill": "until",
    "agian": "again",
    "speach": "speech",
    "writting": "writing"
}