content_formats = [
    "paragraph",
    "bullet points",
    "bulleted list",
    "list",
    "article",
    "essay",
    "summary",
    "note",
    "notes",
    "table",
    "comparison table",
    "timeline",
    "step-by-step",
    "flowchart",
    "code snippet",
    "code example",
    "script",
    "dialogue",
    "Q&A",
    "question and answer",
    "story",
    "poem",
    "report",
    "case study",
    "infographic",
    "chart",
    "graph",
    "presentation",
    "slide deck",
    "email",
    "letter",
    "tweet",
    "thread",
    "caption",
    "captioned image",
    "instruction manual",
    "recipe",
    "outline",
    "abstract",
    "blog post",
    "newsletter",
    "headline",
    "review",
    "explanation",
    "definition",
    "diagnosis",
    "plan",
    "framework",
    "quote",
    "slogan",
    "storyboard",
    "transcript"
]